name: GitHub Pages

on: 
  push:
    branches: 
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Run with setup-python 3.10
        uses: ./
        with:
          python-version: "3.10"
      
      - name: install requirements
        run: pip install -r ./requirements.txt 

      - run: python server.py build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          publish_dir: ./build